apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pythonapp
  description: Python App.
  # Example for optional annotations
  annotations:
    github.com/project-slug: prachponleuuch/pythonapp
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental