name: CI

on:
  push:
    branches: [main]
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set short SHA
      shell: bash
      run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: prachponleuuch/pythonapp:${{ github.sha }}
