name: CI

on:
  push:
    branches: [main]
    paths:
      - "src/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Set short SHA
        shell: bash
        run: echo "SHORT_SHA=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: prachponleuuch/pythonapp:${{ env.SHORT_SHA }}
  cd:
    needs: [ci]
    runs-on: self-hosted
    steps:
      - name: Instal ArgoCD
        shell: bash
        run: |
          curl -ksSL https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          mv ./argocd /usr/local/bin/argocd

      - name: ArgoCD App Sync
        shell: bash
        run: |
          argocd login https://argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync pythonapp
